# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux
    - windows

notifications:
  slack:
    on_success: never
    on_failure: always
    secure: "sa4HE4SjSJfKxs/4wR8YfioggBEe9jDFZSeCDtWFAfzyP/BkVOTvXx1YV3nGbLzXo1zEJ371wB/NdBGFuxVrfeWeGLrT7NMiy5ji7dIGe+nRpcSA3nF1rgniLxx3dHSOj1PVarWvz9220N40mxSr9nyiIN2WuQ4erD2Ia2DLapwd7YJ9Hby8fY+lxLmSybLdjsCCpiK9pV1mZ0hiIX0KczkMrbcfA2ZX0CjIMJTZY5DnMD6XeOqCXv33ZUcMj2pFXq+pvt47HSUh97gp0BplOVuAx+P/Y9/hj1g6J+4iVVEThxO9rfN09zcLDS/d+JD4lAiaj2l+J9l7QJwNunMvpycn0F4W9vcLbC9OpIpwpttBZERbTiBAERcwkfeGdgp4f6Xkc4GStWYGZVgW78AkOltC+/BrUmsrQJI/74nJTEHL3eKNJbAHXQXbTsMFid3fjdsoYejo/ICRlJizSRmv7wkuQW8O4wxU41vhPkbbrFvvOV5IJh+cha6NTjVuU6ZEYjbGoKakKvmT8s8vK88nBGApaz5JTQ4Za05KFwluCuDtKo6z2EZXcH4OPc+lCKEPD3kxJMnd64wJVdSU1xDhC3yYLBWN5ZBmemuAorFPNZL9whxD1Xfnxl55jsVUKimweHktg1A6IxOjjRrwaEA0g3HP7H05hDe2b+D3O8v6+aA="
    if: type = cron
    
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.8
        - PYTEST_COMMAND='pytest'
        - PY_IGNORE_IMPORTMISMATCH=1

    jobs:
        - PYTHON_VERSION=3.6
        - PYTHON_VERSION=3.7 PYTEST_VERSION=4
        - PYTHON_VERSION=3.8 PYTEST_VERSION='<5.4'

stages:
    # only run 2 jobs initially. Using "test" as it cannot be adjusted for the root jobs above.
    - name: Initial tests
    - name: test

jobs:
    include:
        - os: linux
          env: PYTHON_VERSION=3.7 NUMPY_VERSION=stable
          stage: Initial tests

        # Try a run on OSX with latest versions of python and pytest
        - os: osx
          stage: test
          env: PYTHON_VERSION=3.7

        # Try a run against dev pytest
        - stage: test
          env: PYTHON_VERSION=3.8 PYTEST_VERSION=dev

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python -m pip install .

script:
   - $PYTEST_COMMAND --doctest-plus
   - $PYTEST_COMMAND --doctest-plus --doctest-rst
   - $PYTEST_COMMAND --doctest-plus --doctest-rst --text-file-format=tex
